// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAirFlow.Services.Database;

#nullable disable

namespace eAirFlow.Services.Migrations
{
    [DbContext(typeof(_210019Context))]
    [Migration("20251111200215_AddedQrToReservation")]
    partial class AddedQrToReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeatReservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.HasKey("ReservationId", "SeatId")
                        .HasName("PK__SeatRese__E83E92F0F662B9A7");

                    b.HasIndex("SeatId");

                    b.ToTable("SeatReservations", (string)null);
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirlineId"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("AirlineId")
                        .HasName("PK__Airlines__A016BF8090CACD74");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airplane", b =>
                {
                    b.Property<int>("AirplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airplane_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirplaneId"));

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("AirplaneId")
                        .HasName("PK__Airplane__CECD2849B1B94DCA");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.CheckIn", b =>
                {
                    b.Property<int>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("checkin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckinId"));

                    b.Property<DateTime?>("CheckinTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("checkin_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckinId")
                        .HasName("PK__CheckIns__234E2115E4228649");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__C52E0BA830E8EBD2");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.EmployeeAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("JobRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_role");

                    b.Property<string>("JobScope")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("job_scope");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Employee__DA891814BFC506B5");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FlightId");

                    b.ToTable("EmployeeAssignments");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int")
                        .HasColumnName("airplane_id");

                    b.Property<string>("ArrivalLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("arrival_location");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departure_location");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_time");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId")
                        .HasName("PK__Flights__E3705765AA48850A");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightIssue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("issue_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<DateTime?>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("reported_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ReportedBy")
                        .HasColumnType("int")
                        .HasColumnName("reported_by");

                    b.HasKey("IssueId")
                        .HasName("PK__FlightIs__D6185C393F7EBB2B");

                    b.HasIndex("FlightId");

                    b.HasIndex("ReportedBy");

                    b.ToTable("FlightIssues");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__FlightRe__60883D90E9077F41");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("FlightReviews");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.Property<int>("LuggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luggage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuggageId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("LuggageId")
                        .HasName("PK__Luggages__00F3B1704651ABD8");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Luggages");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.LuggageReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("LuggageId")
                        .HasColumnType("int")
                        .HasColumnName("luggage_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ReportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("report_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("report_type");

                    b.HasKey("ReportId")
                        .HasName("PK__LuggageR__779B7C58AE1E15BE");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LuggageId");

                    b.ToTable("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F621D3789");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__ED1FC9EAF4FBAC60");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__99A0E7A4DB79BFD1");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("LuggageOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("reservation_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SeatClassId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__31384C299B9BC2CB");

                    b.HasIndex("FlightId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A4E9A155F");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int")
                        .HasColumnName("airplane_id");

                    b.Property<int?>("SeatClassId")
                        .HasColumnType("int")
                        .HasColumnName("seat_class_id");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.HasKey("SeatId")
                        .HasName("PK__Seats__906DED9C5162B2D2");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("SeatClassId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.SeatClass", b =>
                {
                    b.Property<int>("SeatClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatClassId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PriceMultiplier")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("price_multiplier");

                    b.HasKey("SeatClassId")
                        .HasName("PK__SeatClas__DC348A0F7232C36B");

                    b.ToTable("SeatClasses");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F977AC3CB");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164AA0B9A02")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SeatReservation", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_SeatReservations_Reservations");

                    b.HasOne("eAirFlow.Services.Database.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_SeatReservations_Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.CheckIn", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Reservation", "Reservation")
                        .WithMany("CheckIns")
                        .HasForeignKey("ReservationId")
                        .HasConstraintName("FK_CheckIns_Reservations");

                    b.HasOne("eAirFlow.Services.Database.Seat", "Seat")
                        .WithMany("CheckIns")
                        .HasForeignKey("SeatId")
                        .HasConstraintName("FK_CheckIns_Seats");

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_Employees_Position");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.EmployeeAssignment", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Employee", "Employee")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Employees");

                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Assignments_Flights");

                    b.Navigation("Employee");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .HasConstraintName("FK_Flights_Airlines");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightIssue", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("FlightIssues")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Issues_Flights");

                    b.HasOne("eAirFlow.Services.Database.Employee", "ReportedByNavigation")
                        .WithMany("FlightIssues")
                        .HasForeignKey("ReportedBy")
                        .HasConstraintName("FK_Issues_Employees");

                    b.Navigation("Flight");

                    b.Navigation("ReportedByNavigation");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightReview", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("FlightReviews")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Reviews_Flights");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("FlightReviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("Luggage")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Luggages_Flights");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Luggage")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Luggages_Users");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.LuggageReport", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Employee", "Employee")
                        .WithMany("LuggageReports")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Reports_Employees");

                    b.HasOne("eAirFlow.Services.Database.Luggage", "Luggage")
                        .WithMany("LuggageReports")
                        .HasForeignKey("LuggageId")
                        .HasConstraintName("FK_Reports_Luggages");

                    b.Navigation("Employee");

                    b.Navigation("Luggage");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Notification", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Reservations_Flights");

                    b.HasOne("eAirFlow.Services.Database.Payment", "Payment")
                        .WithMany("Reservations")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Reservations_Payments");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reservations_Users");

                    b.Navigation("Flight");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airplane", "Airplane")
                        .WithMany("Seats")
                        .HasForeignKey("AirplaneId")
                        .HasConstraintName("FK_Seats_Airplanes");

                    b.HasOne("eAirFlow.Services.Database.SeatClass", "SeatClass")
                        .WithMany("Seats")
                        .HasForeignKey("SeatClassId")
                        .HasConstraintName("FK_Seats_SeatClasses");

                    b.Navigation("Airplane");

                    b.Navigation("SeatClass");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.UserRole", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airplane", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("FlightIssues");

                    b.Navigation("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("FlightIssues");

                    b.Navigation("FlightReviews");

                    b.Navigation("Luggage");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.Navigation("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.SeatClass", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.User", b =>
                {
                    b.Navigation("FlightReviews");

                    b.Navigation("Luggage");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reservations");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
