// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAirFlow.Services.Database;

#nullable disable

namespace eAirFlow.Services.Migrations
{
    [DbContext(typeof(_210019Context))]
    [Migration("20251204220345_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eAirFlow.Services.Database.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirlineId"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirlineId");

                    b.HasIndex("AirportId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airplane", b =>
                {
                    b.Property<int>("AirplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirplaneId"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("AirplaneId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.CheckIn", b =>
                {
                    b.Property<int>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckinId"));

                    b.Property<DateTime?>("CheckinTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CheckinId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.EmailConfirmation", b =>
                {
                    b.Property<int>("EmailConfirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailConfirmationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmailConfirmationId");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AirportId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("FlightReviews");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.Property<int>("LuggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuggageId"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LuggageId");

                    b.HasIndex("AirportId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Luggages");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.LuggageReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("LuggageId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LuggageId");

                    b.ToTable("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealTypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MealTypeId");

                    b.ToTable("MealTypes");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("AirportId");

                    b.HasIndex("FlightId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int?>("SeatClassId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("SeatClassId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.SeatClass", b =>
                {
                    b.Property<int>("SeatClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatClassId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatClassId");

                    b.ToTable("SeatClasses");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airline", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airport", "Airport")
                        .WithMany("Airlines")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airplane", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("AirlineId");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.CheckIn", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Reservation", "Reservation")
                        .WithMany("CheckIns")
                        .HasForeignKey("ReservationId");

                    b.HasOne("eAirFlow.Services.Database.Seat", "Seat")
                        .WithMany("CheckIns")
                        .HasForeignKey("SeatId");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Reservation");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.EmailConfirmation", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airport", "Airport")
                        .WithMany("Employees")
                        .HasForeignKey("AirportId");

                    b.HasOne("eAirFlow.Services.Database.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("eAirFlow.Services.Database.Employee", "UserId");

                    b.Navigation("Airport");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.FlightReview", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("FlightReviews")
                        .HasForeignKey("FlightId");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("FlightReviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eAirFlow.Services.Database.Flight", null)
                        .WithMany("Luggage")
                        .HasForeignKey("FlightId");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Luggage")
                        .HasForeignKey("UserId");

                    b.Navigation("Airport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.LuggageReport", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Employee", "Employee")
                        .WithMany("LuggageReports")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("eAirFlow.Services.Database.Luggage", "Luggage")
                        .WithMany("LuggageReports")
                        .HasForeignKey("LuggageId");

                    b.Navigation("Employee");

                    b.Navigation("Luggage");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Notification", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId");

                    b.HasOne("eAirFlow.Services.Database.Airport", "Airport")
                        .WithMany("Reservations")
                        .HasForeignKey("AirportId");

                    b.HasOne("eAirFlow.Services.Database.Flight", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId");

                    b.HasOne("eAirFlow.Services.Database.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId");

                    b.HasOne("eAirFlow.Services.Database.Payment", "Payment")
                        .WithMany("Reservations")
                        .HasForeignKey("PaymentId");

                    b.HasOne("eAirFlow.Services.Database.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId");

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId");

                    b.Navigation("Airplane");

                    b.Navigation("Airport");

                    b.Navigation("Flight");

                    b.Navigation("MealType");

                    b.Navigation("Payment");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Airplane", "Airplane")
                        .WithMany("Seats")
                        .HasForeignKey("AirplaneId");

                    b.HasOne("eAirFlow.Services.Database.SeatClass", "SeatClass")
                        .WithMany("Seats")
                        .HasForeignKey("SeatClassId");

                    b.Navigation("Airplane");

                    b.Navigation("SeatClass");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.UserRole", b =>
                {
                    b.HasOne("eAirFlow.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAirFlow.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airline", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airplane", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Airport", b =>
                {
                    b.Navigation("Airlines");

                    b.Navigation("Employees");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Employee", b =>
                {
                    b.Navigation("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Flight", b =>
                {
                    b.Navigation("FlightReviews");

                    b.Navigation("Luggage");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Luggage", b =>
                {
                    b.Navigation("LuggageReports");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Payment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Reservation", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.Seat", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.SeatClass", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("eAirFlow.Services.Database.User", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("FlightReviews");

                    b.Navigation("Luggage");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reservations");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
